"""OpenCompass config 动态拼装。

路径布局与设计文档 §6.10 一致：
    .../workspace/_in_progress/<job_id>/<run_dir>/configs/<job_id>.py
原子写：临时 .py.tmp → os.replace。
"""
import os
import pprint
from pathlib import Path

from app.core.dataset_registry import DatasetRegistry
from app.core.settings import get_settings
from app.models.request import CreateJobRequest


def _in_progress_dir(job_id: str, run_dir: str) -> Path:
    return (
        Path(get_settings().oc_data_root)
        / "workspace"
        / "_in_progress"
        / job_id
        / run_dir
        / "configs"
    )


def _model_alias(path: str, idx: int) -> str:
    safe = "".join(ch if ch.isalnum() else "_" for ch in path)
    return f"model_{safe.lower()}_{idx}"


def _dataset_alias(abbr: str, idx: int) -> str:
    safe = "".join(
        ch if (ch.isalnum() or "\u4e00" <= ch <= "\u9fff") else "_" for ch in abbr
    )
    return f"dataset_{safe}_{idx}"


def _dump(obj) -> str:
    return pprint.pformat(obj, indent=4, width=88, sort_dicts=False)


def _render(
    dataset_imports,
    dataset_assigns,
    dataset_aliases,
    model_assigns,
    model_aliases,
) -> str:
    lines = ["# Auto-generated by opencompass-app", ""]
    lines.append("from mmengine.config import read_base")
    lines.append("")
    if dataset_imports:
        lines.append("# ===== Built-in datasets (from import) =====")
        lines.append("with read_base():")
        lines.extend(dataset_imports)
        lines.append("")
    if dataset_assigns:
        lines.append("# ===== Custom datasets (inline dict, type in whitelist) =====")
        lines.extend(dataset_assigns)
        lines.append("")
    lines.append(f"datasets = {' + '.join(dataset_aliases)}")
    lines.append("")
    lines.append("# ===== Models (inline dict, type in whitelist) =====")
    lines.extend(model_assigns)
    lines.append("")
    lines.append(f"models = [{', '.join(model_aliases)}]")
    return "\n".join(lines)


async def generate_config(req: CreateJobRequest, run_dir: str = "run_001") -> str:
    """同步生成 OC config 文件，并通过原子写落盘。返回配置文件绝对路径。"""
    config_dir = _in_progress_dir(req.job_id, run_dir)
    config_dir.mkdir(parents=True, exist_ok=True)
    config_path = config_dir / f"{req.job_id}.py"

    dataset_imports: list[str] = []
    dataset_assigns: list[str] = []
    dataset_aliases: list[str] = []
    for idx, ds in enumerate(req.datasets):
        item = ds.model_dump(exclude_none=True)
        if set(item.keys()) <= {"abbr"}:
            mod, var = DatasetRegistry.resolve_builtin(item["abbr"])
            dataset_imports.append(f"    from {mod} import {var}")
            dataset_aliases.append(var)
        else:
            alias = _dataset_alias(item["abbr"], idx)
            dataset_assigns.append(f"{alias} = {_dump([item])}")
            dataset_aliases.append(alias)

    model_assigns: list[str] = []
    model_aliases: list[str] = []
    for idx, m in enumerate(req.models):
        alias = _model_alias(m.path, idx)
        model_assigns.append(f"{alias} = {_dump(m.model_dump())}")
        model_aliases.append(alias)

    source = _render(
        dataset_imports,
        dataset_assigns,
        dataset_aliases,
        model_assigns,
        model_aliases,
    )

    tmp = config_path.with_suffix(".py.tmp")
    tmp.write_text(source, encoding="utf-8")
    os.replace(tmp, config_path)
    return str(config_path)
